version: "2"

services:
  nginx:
    image: nginx
    container_name: proxy
    restart: always
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./public/:/var/www/public/
    ports:
      - 80:80
    networks:
      - app-network
  app:
    image: php:7.2-fpm
    container_name: MyProject
    restart: always
    volumes:
      - ./public/:/var/www/public/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
